
spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: cIlhFslYAFqyoWJywwrhhrfeMGgRiQrL

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: onboarding-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: true
    hostname: ${RAILWAY_STATIC_URL}

#spring:
#  application:
#    name: onboarding-service
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/onboarding
#    username: root
#    password: cassillas1nengi

server:
  port: 8085
