spring:
  application:
    name: onboarding-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/onboarding
    username: root
    password: cassillas1nengi

server:
  port: 8085
